#!/usr/bin/env python3
"""Regenerate the built-in Migu1M UI/terminal fonts (lib/EpdFont/builtinFonts/migu1m_term_*.h).

Coverage: ASCII, Japanese punctuation, hiragana, katakana, full/half-width
forms, and every JIS X 0208 level-1 kanji (rows 16-47, 2965 characters).

The previous headers were generated by an unrecorded script whose kanji range
was shifted: 527 level-1 kanji (愛, 海, 気, 心, 山, ...) were missing and 32
level-2 kanji from row 48 were included instead.

Requires the Migu 1M TTFs (https://mix-mplus-ipa.osdn.jp/migu/) and the
Python deps in lib/EpdFont/scripts/requirements.txt.

    python3 scripts/build_migu_ui_fonts.py \\
        --regular ~/Library/Fonts/migu-1m-regular.ttf \\
        --bold ~/Library/Fonts/migu-1m-bold.ttf
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONVERTER = os.path.join(ROOT, "lib", "EpdFont", "scripts", "fontconvert_sdcard.py")
OUT_DIR = os.path.join(ROOT, "lib", "EpdFont", "builtinFonts")

SIZES = (8, 10, 12)

# Non-kanji ranges carried over unchanged from the previous headers.
BASE_RANGES = [
    (0x0020, 0x007E),  # ASCII
    (0x00AB, 0x00AB),  # «
    (0x00BB, 0x00BB),  # »
    (0x2018, 0x201F),  # curly quotes
    (0x2026, 0x2026),  # …
    (0x3000, 0x3020),  # CJK punctuation
    (0x3030, 0x3035),
    (0x303B, 0x303D),
    (0x3041, 0x3096),  # hiragana
    (0x3099, 0x30FF),  # voicing marks, katakana
    (0xFF01, 0xFF9F),  # full-width ASCII, half-width katakana
    (0xFFE0, 0xFFE6),  # full-width symbols
]


def jis_level1_kanji() -> list[int]:
    cps = []
    for row in range(16, 48):
        for col in range(1, 95):
            try:
                cps.append(ord(bytes([0xA0 + row, 0xA0 + col]).decode("euc_jp")))
            except UnicodeDecodeError:
                pass  # unassigned cells at the end of row 47
    return cps


def to_ranges(cps: set[int]) -> list[tuple[int, int]]:
    ranges: list[list[int]] = []
    for cp in sorted(cps):
        if ranges and cp == ranges[-1][1] + 1:
            ranges[-1][1] = cp
        else:
            ranges.append([cp, cp])
    return [(a, b) for a, b in ranges]


def write_header(data: bytes, size: int, path: str) -> None:
    name = f"MIGU1M_TERM_{size:02d}"
    with open(path, "w", encoding="utf-8") as f:
        f.write(f"// Auto-generated by scripts/build_migu_ui_fonts.py — Migu1M {size}pt, JIS X 0208 level-1 kanji\n")
        f.write("#pragma once\n#include <stddef.h>\n\n")
        f.write(f"static const unsigned char {name}[] PROGMEM = {{\n")
        for i in range(0, len(data), 16):
            f.write("    " + ",".join(f"0x{b:02x}" for b in data[i : i + 16]) + ",\n")
        f.write("};\n")
        f.write(f"static const size_t {name}_SIZE = {len(data)}UL;\n")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--regular", required=True, help="migu-1m-regular.ttf")
    ap.add_argument("--bold", required=True, help="migu-1m-bold.ttf")
    args = ap.parse_args()

    kanji = jis_level1_kanji()
    assert len(kanji) == 2965, len(kanji)
    cps = set(kanji)
    for a, b in BASE_RANGES:
        cps.update(range(a, b + 1))
    intervals = ",".join(f"(0x{a:04X}-0x{b:04X})" for a, b in to_ranges(cps))

    with tempfile.TemporaryDirectory() as tmp:
        for size in SIZES:
            out = os.path.join(tmp, f"migu_{size}.cpfont")
            subprocess.run(
                [sys.executable, CONVERTER, "--regular", args.regular, "--bold", args.bold, "--size", str(size),
                 "--intervals", intervals, "-o", out],
                check=True, cwd=os.path.dirname(CONVERTER), stdout=subprocess.DEVNULL)
            with open(out, "rb") as f:
                data = f.read()
            path = os.path.join(OUT_DIR, f"migu1m_term_{size:02d}.h")
            write_header(data, size, path)
            print(f"{os.path.relpath(path, ROOT)}: {len(data)} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
